// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    ContactUs: typeof import('./components/ContactUs.vue')['default']
    Event: typeof import('../../src/Event.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Markdown: typeof import('./components/Markdown.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
